spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3307/rds_sys?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall

    initial-size: 1
    min-idle: 1
    max-active: 20

    max-wait: 60000

    time-between-evict-runs-millis: 60000

    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false

    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
  #    initialization-mode: always

#    schema:
#      - ../rds_sys.sql